### ISSUE TITLE
im getting a error message wasnt able to transfer, maybe not enough space but i got space 

### ISSUE THREAD

**Issue by VERDERAJME** [cybercase/webminidisc#80] opened 2022-01-20 23:15 UTC
the webminidisc, is not transfering music, there was comment below WMA not support,but  it wont transfer any songs that are in MP3 FORMAT neither , i get message no enough space, i got space,. my second question are ya able to hear sound on PC?  any help be appreciated

**Comment by asivery** [comment] 2022-01-22 12:49
@VERDERAJME What player are you using?
As for the second question, no. It's impossible - it's a limitation on the NetMD protocol.

**Comment by zarkone** [comment] 2022-03-16 16:29
same happens for me, `mz-n707`, various formats. It happened to me twice -- when I tried to record 40 tracks and 52 tracks, respectively. I've got an impression that it 'full' means that TOC is full -- because of amount of tracks and because I've got the message on the final, TOC edit part -- after some time on TOC edit it gives me back this message. 

Hope this is helpful, feel free to ping me if I can help with any kind of testing. 

I also didn't look at chrome console -- going to check it next time as well.

**Comment by loformat** [comment] 2022-03-28 17:37
Hey guys!  The same for me. I've got mz-n707. Win10Pro with clean Chrome installed only for this purpose.  Absolutely the same issue. Have tried it several times. And one time it started to upload the file, but suddenly stopped at some 60% and spotted a message regarding "not enough space', but the disc has been wiped. Tried to wipe couple of times  - the same result. Enable to edit TOC though.
Either it is some kind of glitch for some certain model or... please advise. 
Thanks

**Comment by zarkone** [comment] 2022-03-28 19:09
I've actually got netmd deck today -- will check on it as well as soon as I get usb-b cable.. It is just, I think that lazer on my n

**Comment by asivery** [comment] 2022-03-28 23:19
Hello @zarkone, @loformat 
It's a known bug. It is confirmed to happen on the N707, N505, N1 and some others. I am working on a fix, but because I don't own any of these devices, it's not that easy for me to find out what's causing it. If possible, please attach the JS Console logs. 
[This version](https://web.minidisc.wiki) should write more detailed logs, as to what exactly fails.

**Comment by zarkone** [comment] 2022-03-29 09:21
hey @asivery :wave: thanks for the version, will check it. I also think that we can pair on that one -- my device, your skills :smile: but I'll probably need to prepare the env first

**Comment by assinder** [comment] 2022-05-17 16:39
Hi. I've just got a Sony MDS-JE780 which throws up the same error almost immediately. My MD Walkman (MZ-N510) works fine. Pity because I bought the deck specifically for transferring music from PC to MD. Is there any chance of a fix or should I give up. Thanks for any advice.

**Comment by zarkone** [comment] 2022-05-18 07:40
I've also bought a deck, MDS-JB980 for same purpose because of constant fails with my N707 -- and it records perfectly fine with webminidisc :+1:

**Comment by assinder** [comment] 2022-05-18 11:10
That's interesting, thank you. Hope I haven't bought an incompatible deck with the 780. I have a laser cleaner disc coming and hope that might help. I have got it working via optical but that's real time recording of course. Would be great if there was a fix. Thanks again.

**Comment by asivery** [comment] 2022-06-03 15:29
@assinder @zarkone Sorry for not responding for so long. Could you please attach the JS Console logs from https://web.minidisc.wiki after the page has crashed?
I just want to confirm the exact error you're having, and the original version's logs omit the exact command sent to the device when it crashes. The 'not enough space' error is an overarching error - it gets triggered whenever something goes wrong with the transfer. Space has nothing to do with it.
I'm working on a large update that might be able to resolve these problems.

**Comment by assinder** [comment] 2022-06-04 09:40
Thank you for your efforts on this, it is very frustrating. Apologies for being dim but I'm not sure what the JS Console log is - is this it:
 Error uploading to device. There might not be enough space left, or an unknown error occurred.
Hope it helps. The programme is brilliant and has revived my interest in MDs, which I love, so it would be perfect to get the deck working.
Thanks again.

**Comment by asivery** [comment] 2022-06-04 10:30
@assinder Apologies for being unclear. If you right click anywhere on the page, in the context menu there should be an option called 'Inspect'. It should open up the devtools. Select the 'Console' tab, right click on the text displayed there, and select 'Save as', then attach that file here.

**Comment by assinder** [comment] 2022-06-04 12:52
No it's absolutely my inexperience. Here it is (I hope).
[web.minidisc.wiki-1654347046253.log](https://github.com/cybercase/webminidisc/files/8837728/web.minidisc.wiki-1654347046253.log)

**Comment by asivery** [comment] 2022-06-18 23:28
@assinder Thanks a lot for the logs. I'll see what I can do.

**Comment by assinder** [comment] 2022-06-19 10:14
That would be brilliant. Many thanks for all your work on this.

**Comment by asivery** [comment] 2022-06-22 13:07
@assinder Please check out https://web.minidisc.wiki/. I've uploaded a new version there.

**Comment by assinder** [comment] 2022-06-22 18:12
Hi. I've tried that but now I get the "Oops something went wrong..." error. Here's thew new log. Thanks again.
 https://web.minidisc.wiki/

**Comment by assinder** [comment] 2022-06-22 18:15
Sorry my mistake, here it is.
[web.minidisc.wiki-1655921424565.log](https://github.com/cybercase/webminidisc/files/8960357/web.minidisc.wiki-1655921424565.log)

**Comment by asivery** [comment] 2022-06-27 14:06
@assinder I have pushed another update, please let me know if the issue has been solved. Also, before you test the new version, please power cycle your device and force-refresh the page (Ctrl+Shift+R).

**Comment by asivery** [comment] 2022-06-27 18:38
@assinder You're using the wrong site. Use https://web.minidisc.wiki/

**Comment by assinder** [comment] 2022-06-27 18:54
Apologies, my mistake. Still no joy....
[web.minidisc.wiki-1656355935192.log](https://github.com/cybercase/webminidisc/files/8994815/web.minidisc.wiki-1656355935192.log)

**Comment by assinder** [comment] 2022-06-27 20:05
Tried just now. Platinum says it has converted to wav and attempts to transfer but fails. The deck shows the connect request even when it appears connected successfully. I don't want to keep wasting your time with this if you think it might be terminal!
[-1656360128370.log](https://github.com/cybercase/webminidisc/files/8995244/-1656360128370.log)

**Comment by asivery** [comment] 2022-06-28 09:59
@assinder I've been talking to the original linux-minidisc developers, it seems your device doesn't support the key used by both linux-minidisc and netmd-js (which is based on linux-minidisc, so no surprises there). It should be possible to add support for your device. Would you mind joining the Minidisc.wiki discord server (https://minidisc.wiki/discord)? It's easier to chat on that than on GH issues.

**Comment by assinder** [comment] 2022-06-28 10:48
I've joined discord but you will have guessed I am a complete newbie to all this so please bear with me. What steps should I take?

**Comment by asivery** [comment] 2022-06-28 11:52
The unit is physically damaged - leaf ID = ffffffffffffffff

**Closed by asivery** 2022-06-28 11:52 UTC
