### ISSUE TITLE
Oops… Something unexpected happened.

### ISSUE THREAD

**Issue by ACTPOHABT-us** [cybercase/webminidisc#21] opened 2020-09-24 12:14 UTC
The app used to work fine until it froze recording a disc and now no longer works with the below error:

Oops… Something unexpected happened.
Try to restart the app. If the error persists, try the followings:
Use your browser in incognito mode.
Use a blank MiniDisc.
Try to use Web MiniDisc on another computer.
If this does not solve the error, your unit might not be supported yet or you have encountered a bug. The full error is reported in the JS console.
<img width="734" alt="Screen Shot 2020-09-24 at 08 12 32" src="https://user-images.githubusercontent.com/37157068/94143454-d815f800-fe3d-11ea-9122-1a074c1ca280.png">

If anyone knows how to resolve it, please let me know (tried clearing cookies, reinstalling the app, incognito window, same result)

**Comment by cybercase** [comment] 2020-09-24 12:38
Hello @ACTPOHABT-us 
I've recently pushed an update that might be the cause of this error.
Could you open the JS console, reload the app (by pressing the refresh button in the browser) and take a screenshot of the reported error?

To open the js console, just use the View => Developer => Javascript Console menu. 

Thanks

**Comment by cybercase** [comment] 2020-09-24 12:58
@ACTPOHABT-us Also, would you mind sharing your device brand and model?

**Comment by ACTPOHABT-us** [comment] 2020-09-24 13:05
Hi Stefano,

It’s Sony MZ-M10 (same as RH910) Hi-MD. The console screenshot was without
the MD connected, not sure if that makes a difference. If you need me to
connect the MD, I can do it after work today.

**Comment by cybercase** [comment] 2020-09-24 13:17
Thanks @ACTPOHABT-us , no rush, take the screenshot whenever you've time.

I'm just interested in the error message printed in the JS console when the Oops dialog pops up.
So, just make sure you've the JS Console opened before browsing to the Web MiniDisc app.

**Comment by ACTPOHABT-us** [comment] 2020-09-24 13:22
Will do, thank you Stefano. I will let you know.

**Comment by cybercase** [comment] 2020-09-24 16:57
This is how the screenshot should look like
<img width="1438" alt="Screenshot 2020-09-24 at 18 56 30" src="https://user-images.githubusercontent.com/1076854/94176012-c2352100-fe97-11ea-8a4e-8f0501b0684d.png">

**Comment by ACTPOHABT-us** [comment] 2020-09-25 01:59
Hi Stefano,

here it is:
<img width="1629" alt="Screen Shot 2020-09-24 at 21 59 01" src="https://user-images.githubusercontent.com/37157068/94217916-2ca68b00-feb1-11ea-81b4-9ac2009d09a3.png">

**Comment by cybercase** [comment] 2020-09-25 02:47
Thanks @ACTPOHABT-us .
I've found the root cause of the error and fixed it. Unfortunately there are slight differences in the communication protocol between one device and the other. Of course, everything was working fine with my mz-n710, but clearly it wasn't with your device.

By the way, now it should be fixed and the next time you open the app you'll get the new version.
To make sure you're on the lastest app version, just check that there isn't the "New content is available..." message in the console. If the message is still there, just close the browser and reopen it.

Let me know if the fix works

**Comment by ACTPOHABT-us** [comment] 2020-09-25 03:15
Thank you so much Stefano for the quick fix, I really appreciate it! Started a transfer, working great so far! :)

**Comment by ACTPOHABT-us** [comment] 2020-09-25 03:32
Thank you again! Transfer completed successfully, not sure if these are relevant or make any difference, in case you need it:
<img width="1601" alt="Screen Shot 2020-09-24 at 23 26 00" src="https://user-images.githubusercontent.com/37157068/94223317-a5134900-febd-11ea-80db-fb04e23365a0.png">

**Closed** 2020-09-25 08:57 UTC
